services:
  e-commerce:
    build:
      context: .
    container_name: e-commerce-backend
    depends_on:
      - database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/e-commerce-basic
    ports:
      - "8080:8080"
    volumes:
      - upload-data:/var/www/upload
    networks:
      - mynetwork

  database:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce
    ports:
      - "5432:5432"
    networks:
      - mynetwork


volumes:
  upload-data:
    driver: local


networks:
  mynetwork:
    driver: bridge
