spring:
  application:
    name: e-commerce-basic


  # http://localhost:8080/oauth2/authorization/google
  # Datasource Configuration (Veritabanı Bağlantısı)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/e_commerce_basic}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  # JPA Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}

upload:
  dir: /var/www/upload/
  url: http://localhost:8080/
  file:
    url: http://localhost:8080/api/v1/upload/

cookie:
  refreshTokenCookie:
    secure: false
    refreshmaxAge: 604800
    sameSite: None
    path: /api/v1/auth

jwt:
  accessExp: 900000
  refreshAge: 604800000
  secret: C2VB987vxNVXvn543xVvxmVX7BCVM432NxvbvbnVXncm
  jwtheader: Authorization

regex:
  email: ".*"
  password: ".*"

payment:
  iyzico:
    apiKey: sandbox-JbYzNd3TVSGRKgrKKFiM5Ha7MJP7YZSo
    secretKey: sandbox-mvXUSAUVAUhj7pNFFsbrKvWjGL5cEaUP
    baseUrl: https://sandbox-api.iyzipay.com
    callBack: /api/v1/payment/payCallBack

domain:
  test: https://litysofttest1.site